---
title: "ESM242_Final"
author: "Kirby Bartlett"
date: "November 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries 
```{r}
library(tidyverse)
library(cowplot)

#if("dplyr" %in% (.packages())){
 #         detach("package:dplyr", unload=TRUE) 
#          detach("package:plyr", unload=TRUE) 
#} 
library(plyr)
library(dplyr)
```
Read in data
```{r}
SGMA_2040 <- read_csv(file.path("Data", "SGMA_Model.csv"))
Open_Access <- read_csv(file.path("Data", "OpenAccess.csv"))
SGMA_2060 <- read_csv(file.path("Data", "SGMA_2060.csv"))
SGMA_2080 <- read_csv(file.path("Data", "SGMA2080.csv"))
SGMA_2100 <- read_csv(file.path("Data", "SGMA2100.csv"))
Artifical_Recharge <- read_csv(file.path("Data", "Artificial_Recharge.csv"))
Recharge_Linear_Decline <- read_csv(file.path("Data", "Recharge_Linear_Decline.csv"))
merged_withdrawls <- read_csv(file.path("Data", "merged_withdrawls.csv"))
```

Merging SGMA and Open Access Data Frames 
```{r}

SGMA_2040 <- SGMA_2040 %>% 
  dplyr::rename(SGMA_2040_Withdrawals = Withdrawals) 
  
Open_Access <- Open_Access %>% 
  dplyr::rename(Open_Withdrawl = Withdrawals) 

#merged_withdrawls <- dplyr::left_join(SGMA_2040, Open_Access, by =c('t')) %>% 
  # tidyr::gather(key = 'Withdrawl_Type', value = 'Withdrawl', SGMA_2040_Withdrawals, Open_Withdrawl)

```


SGMA vs Open Access
```{r}
colors <- c('cyan4', 'indianred3')

direct_labels <-  merged_withdrawls %>% 
  dplyr::group_by(Withdrawl_Type) %>%
  dplyr::summarize(y = min(Withdrawl))

write_csv(merged_withdrawls, path = "~/GitHub/ESM242_Final/Data/merged_withdrawls.csv")

line_plot <- merged_withdrawls %>%
  ggplot(aes(t, Withdrawl )) +
  geom_line( aes(group = Withdrawl_Type, color = Withdrawl_Type), size = 1) +
  scale_color_manual(values=colors) +
  theme_minimal_hgrid() +
  scale_x_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Withdrawls in Acre Feet") +
  theme(legend.position = "none") 
  
direct_labels_axis <- axis_canvas(line_plot, axis = "y") +
  geom_text(
 data = direct_labels,
 aes(y = y, label = c("Open Access", "SGMA")),
 x = .05,
 size = 4.5,
 hjust = 0
  )

p_direct_labels <-  insert_yaxis_grob(line_plot, direct_labels_axis)

ggdraw(p_direct_labels)
```

2040 vs 2060 vs 2080 vs 2100
```{r}

SGMA_2060  <- SGMA_2060  %>% 
   dplyr::rename(SGMA_2060_Withdrawals = Withdrawals) 
  
SGMA_2080  <- SGMA_2080 %>% 
   dplyr::rename(SGMA_2080_Withdrawals = Withdrawals) 

SGMA_2100  <- SGMA_2100 %>% 
   dplyr::rename(SGMA_2100_Withdrawals = Withdrawals) 



SGMA_years_plot <-
  ggplot() +
  geom_line(data = SGMA_2040, aes(t, SGMA_2040_Withdrawals), size = 1, colour = 'indianred3') +
  geom_line(data = SGMA_2060, aes(t, SGMA_2060_Withdrawals), size = 1, colour = 'cyan4') +
  geom_line(data = SGMA_2080, aes(t, SGMA_2080_Withdrawals), size = 1, colour = "#F1A94E") +
  geom_line(data = SGMA_2100, aes(t, SGMA_2100_Withdrawals), size = 1, colour = "#669900") +
  scale_color_manual(values=colors) +
  theme_minimal_hgrid() +
  #scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Withdrawls in Acre Feet") +
  theme(legend.position = "none") +
  xlim(2020,2100.5)

SGMA_years_plot

```

Artificial Recharge Plot 
```{r}
Artificial_plot <- ggplot() +
  geom_line(data = SGMA_2040, aes(t, SGMA_2040_Withdrawals), size = 1, colour = 'indianred3') +
  geom_line(data = Artifical_Recharge, aes(t, Withdrawals), size = 1, colour = 'cyan4') +
  scale_color_manual(values=colors) +
  theme_minimal_hgrid() +
  #scale_x_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Withdrawls in Acre Feet") +
  theme(legend.position = "none") +
  xlim(2020,2040.5)

Artificial_plot
```

Linear Decline Plot 
```{r}
Linear_plot <- ggplot(data = Recharge_Linear_Decline, aes(t, Withdrawals)) +
  geom_line(size = 1) +
  scale_color_manual(values=colors) +
  theme_minimal_hgrid() +
  #scale_x_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Withdrawls in Acre Feet") +
  theme(legend.position = "none") +
  xlim(2020,2040.5)

Linear_plot 
```

Height over time 
```{r}

SGMA_2060  <- SGMA_2060  %>% 
   dplyr::rename(SGMA_2060_height = Height) 
  
SGMA_2080  <- SGMA_2080 %>% 
   dplyr::rename(SGMA_2080_height = Height) 

SGMA_2100  <- SGMA_2100 %>% 
   dplyr::rename(SGMA_2100_height = Height) 

SGMA_2040 <- SGMA_2040 %>% 
  dplyr::rename(SGMA_2040_height = Height) 





SGMA_height_plot <-
  ggplot() +
  geom_line(data = SGMA_2040, aes(t, SGMA_2040_height), size = 1, colour = 'indianred3') +
  geom_line(data = SGMA_2060, aes(t, SGMA_2060_height), size = 1, colour = 'cyan4') +
  geom_line(data = SGMA_2080, aes(t, SGMA_2080_height), size = 1, colour = "#F1A94E") +
  geom_line(data = SGMA_2100, aes(t, SGMA_2100_height), size = 1, colour = "#669900") +
  scale_color_manual(values=colors) +
  theme_minimal_hgrid() +
  #scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Watertable Height") +
  theme(legend.position = "none") +
  xlim(2020,2100.5) 

SGMA_height_plot

```

Artififical Recharge vs Open Access 
```{r}
Water_Table <- read_csv(file.path("Data", "Water_Table.csv"))

colors_1 <- c('indianred3', 'cyan4')

Water_Gather <-  tidyr::gather(data = Water_Table, key = 'Table_Type', value = 'Height_ft', height_Recharge, Height_Open)

direct_labels <-  Water_Gather %>% 
  dplyr::group_by(Table_Type) %>%
  dplyr::summarize(y = min(Height_ft))


line_plot_height <- Water_Gather %>%
  ggplot(aes(t, Height_ft)) +
  geom_line( aes(group = Table_Type, color = Table_Type), size = 1) +
  scale_color_manual(values=colors_1) +
  theme_minimal_hgrid() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Water Table Height (ft)") +
  theme(legend.position = "none") 
  
direct_labels_axis <- axis_canvas(line_plot_height, axis = "y") +
  geom_text(
 data = direct_labels,
 aes(y = y, label = stringr::str_wrap(c("No Artifical Recharge", "Artificial Recharge Included"),1)),
 x = .05,
 size = 4.5,
 hjust = 0,
 vjust = -0.05
  )

p_direct_labels <-  insert_yaxis_grob(line_plot_height, direct_labels_axis)

ggdraw(p_direct_labels)

```



Withdrawls for open vs recharge 
```{r}
Water_Table <- read_csv(file.path("Data", "Water_Table.csv"))

colors_1 <- c('indianred3', 'cyan4')

Water_Gather_withdraw <-  tidyr::gather(data = Water_Table, key = 'Table_Type', value = 'Withdrawls', withdrawals_Recharge, Withdrawals_Open)

direct_labels <-  Water_Gather_withdraw %>% 
  dplyr::group_by(Table_Type) %>%
  dplyr::summarize(y = min(Height_ft))


line_plot_height <- Water_Gather_withdraw %>%
  ggplot(aes(t, Withdrawls)) +
  geom_line( aes(group = Table_Type, color = Table_Type), size = 1) +
  scale_color_manual(values=colors_1) +
  theme_minimal_hgrid() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "Withdrawls (acre feet)") +
  theme(legend.position = "none") 
  
direct_labels_axis <- axis_canvas(line_plot_height, axis = "y") +
  geom_text(
 data = direct_labels,
 aes(y = y, label = stringr::str_wrap(c("No Artifical Recharge", "Artificial Recharge Included"),1)),
 x = .05,
 size = 4.5,
 hjust = 0,
 vjust = -0.05
  )

p_direct_labels <-  insert_yaxis_grob(line_plot_height, direct_labels_axis)

ggdraw(p_direct_labels)
```

